export default [
	{
		createDate: new Date('January 31, 2021 17:00:00'),
		title: 'Sort by status',
		desc: 'Try clicking the priority buttons above',
		project: 'Portfolio',
		dueDate: new Date('October 4, 2022 11:13:00'),
		priority: 'high',
		completed: true,
	},
	{
		createDate: new Date('January 31, 2021 17:00:00'),
		title: 'Sort by Project',
		desc: 'Try clicking the filter buttons to the left',
		project: 'Portfolio',
		dueDate: new Date('March 3, 2073 11:13:00'),
		priority: 'normal',
		completed: false,
	},
	{
		createDate: new Date('January 31, 2021 17:00:00'),
		title: 'Create a new Todo',
		desc: "Try clicking 'New Task' button to the left",
		project: 'Portfolio',
		dueDate: new Date('July 30, 2026 12:13:00'),
		priority: 'normal',
		completed: false,
	},
	{
		createDate: new Date('January 31, 2021 17:00:00'),
		title: 'Sort by priority',
		desc: 'Try clicking priority filter buttons above',
		project: 'Portfolio',
		dueDate: new Date('December 9, 2023 12:13:00'),
		priority: 'normal',
		completed: false,
	},
	{
		createDate: new Date('January 31, 2021 17:00:00'),
		title: 'Hire Ty',
		desc: 'Because you want to work with him!',
		project: 'Personal',
		dueDate: new Date('March 1, 2021 12:13:00'),
		priority: 'high',
		completed: false,
	},
];
